jobs:
- job: x64
  pool:
    vmImage: 'Ubuntu-18.04'
  steps:
  - template: build.yml
    parameters:
      arch: x64
      tag: bionic

- job: armhf
  pool:
    vmImage: 'Ubuntu-16.04'
  steps:
  - template: build.yml
    parameters:
      qemu: 'true'
      arch: armhf
      tag: armhf-temp

- job: arm64
  pool:
    vmImage: 'Ubuntu-16.04'
  steps:
  - template: build.yml
    parameters:
      qemu: 'true'
      arch: arm64
      tag: arm64-temp

- job: alpine
  pool:
    vmImage: 'Ubuntu-16.04'
  steps:
  - template: build.yml
    parameters:
      arch: alpine
      tag: alpine-temp

- job: stretch_arm64
  pool:
    vmImage: 'Ubuntu-16.04'
  steps:
  - template: build.yml
    parameters:
      arch: stretch-arm64
      tag: stretch-arm64-temp

- job: stretch_armhf
  pool:
    vmImage: 'Ubuntu-16.04'
  steps:
  - template: build.yml
    parameters:
      arch: stretch-armhf
      tag: stretch-arm64-temp

- job: buster_arm64
  pool:
    vmImage: 'Ubuntu-16.04'
  steps:
  - template: build.yml
    parameters:
      arch: buster-arm64
      tag: buster-arm64-temp

- job: buster_armhf
  pool:
    vmImage: 'Ubuntu-16.04'
  steps:
  - template: build.yml
    parameters:
      arch: buster-armhf
      tag: buster-armhf-temp
